gKey = 'AIzaSyD6HTdJLDVNyYQZnDp1kZcG0Pks3sRRNh4'
days =['mon_fri','saturday','sunday']
lineNameNamePath = '//div[@id="web_traseu"]/b/text()'
stationPath = '//div[@id="statie_web"]/b/text()'
lineNameNrPath ='//div[@id="linia_web"]/b/text()'
hasExtraStationsPath = '//div[@id="nota"]'
hasHandicapRidePath = '//div[contains(@id,"dizabilitati")]'
minXpath = '//div[@id="tabel2"][{0}]/div[@id="web_class_minutes"][{1}]/div'
hourXpath = '//div[@id="tabel2"][{0}]/div[@id="web_class_hours"][{1}]/text()'
hoursPath = '//div[@id="tabel2"][{0}]/div[@id="web_class_hours"]/text()'
allLinesXpath = '//a[contains(@class,"linia")]/@href'
viewSchendulerXpath = '//a[@class="orar-linie"]/@href'
viewOldVersonSchenXpath = '//h2[@class="titlu-pagina"]/a/@href'
startUrl = 'http://www.ratbv.ro/trasee-si-orare/'